version: "3.9"
services:
  gotapp:
    build: ./first-app
    ports:
      - 8500:8500
  rnmapp:
    build: ./second-app
    ports:
      - 8501:8500
  navbar:
    build: ./navbar
    ports:
      - 8502:8500
  root:
    build: ./root-config
    ports:
      - 9000:9000
