FROM node:18-alpine

RUN ["mkdir", "-p", "/usr/src", "/usr/build"]
COPY ./package.json /usr/src
WORKDIR /usr/src
RUN ["npm", "i", "--prefer-offline", "--no-audit"]

COPY . /usr/src
RUN ["npm", "run", "build"]
RUN ["cp", "-r", "/usr/src/dist/.", "/usr/build"]

CMD [ "npx", "serve", "/usr/src/dist"]