FROM node:18-alpine

RUN ["mkdir", "-p", "/usr/src", "/usr/build"]
COPY ./package.json /usr/src
WORKDIR /usr/src
RUN ["npm", "i", "--prefer-offline", "--no-audit"]

COPY . /usr/src
RUN ["npm", "run", "build"]
RUN ["mv", "/usr/src/dist", "/usr/build/got"]