FROM node:18-alpine

RUN ["mkdir", "-p", "/usr/src", "/usr/build"]
WORKDIR /usr/src
COPY ./package.json .
COPY ./package-lock.json .
RUN ["npm", "ci", "--prefer-offline", "--no-audit"]

COPY . .
RUN ["npm", "run", "build"]
CMD ["mv", "./dist", "/usr/build/got"]